### ISSUE TITLE
HTTP Error - Search Endpoint Down

### ISSUE THREAD

**Issue by lucasstark** [johnshopkins/mindbreeze-example#1]
Trying to run the example I encountered "HTTP Error". 

I don't think the search endpoint is operational anymore.

**Comment by jenwachter** [comment]
You are getting an HTTP error because the search endpoint used in this example is internal to Johns Hopkins University and is not publicly available. Change the [$url](https://github.com/johnshopkins/mindbreeze-example/blob/master/src/Request.php#L7) to your own mindbreeze endpoint and it should work for you.
